
version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: arn:aws:ecs:ap-south-1:266735821233:task-definition/poc-td:4
        LoadBalancerInfo:
          ContainerName: my-cont
          ContainerPort: 80
